"""Add chip column

Revision ID: 317dccce3145
Revises: ddb8f1df0ecd
Create Date: 2021-10-27 10:22:34.020247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317dccce3145'
down_revision = 'ddb8f1df0ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dog', sa.Column('chip', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dog', 'chip')
    # ### end Alembic commands ###
