"""Add age to Dog

Revision ID: ddb8f1df0ecd
Revises: f5832f5b64df
Create Date: 2021-10-27 09:50:29.267247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb8f1df0ecd'
down_revision = 'f5832f5b64df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dog', sa.Column('age', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dog', 'age')
    # ### end Alembic commands ###
